"""init schema

Revision ID: 04be6d39f33b
Revises: 
Create Date: 2026-07-07 07:09:49.067608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04be6d39f33b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parametre_systeme',
    sa.Column('id_parametre', sa.Integer(), nullable=False),
    sa.Column('nom_parametre', sa.String(length=100), nullable=False),
    sa.Column('valeur', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_parametre'),
    sa.UniqueConstraint('nom_parametre')
    )
    op.create_table('permission',
    sa.Column('id_permission', sa.Integer(), nullable=False),
    sa.Column('nom_permission', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_permission'),
    sa.UniqueConstraint('nom_permission')
    )
    op.create_table('role',
    sa.Column('id_role', sa.Integer(), nullable=False),
    sa.Column('nom_role', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_role'),
    sa.UniqueConstraint('nom_role')
    )
    op.create_table('service',
    sa.Column('id_service', sa.Integer(), nullable=False),
    sa.Column('nom_service', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_service'),
    sa.UniqueConstraint('nom_service')
    )
    op.create_table('agent',
    sa.Column('id_agent', sa.Integer(), nullable=False),
    sa.Column('matricule', sa.String(length=30), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('fonction', sa.String(length=150), nullable=True),
    sa.Column('statut', sa.Enum('actif', 'desactive', name='statut_agent'), server_default='actif', nullable=False),
    sa.Column('consentement_facial', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id_service', sa.Integer(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_service'], ['service.id_service'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_agent')
    )
    op.create_index(op.f('ix_agent_id_service'), 'agent', ['id_service'], unique=False)
    op.create_index(op.f('ix_agent_matricule'), 'agent', ['matricule'], unique=True)
    op.create_index(op.f('ix_agent_nom'), 'agent', ['nom'], unique=False)
    op.create_index(op.f('ix_agent_prenom'), 'agent', ['prenom'], unique=False)
    op.create_table('horaire_reference',
    sa.Column('id_horaire', sa.Integer(), nullable=False),
    sa.Column('id_service', sa.Integer(), nullable=True),
    sa.Column('heure_debut', sa.Time(), nullable=False),
    sa.Column('heure_fin', sa.Time(), nullable=False),
    sa.Column('jour_semaine', sa.Enum('lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi', 'samedi', 'dimanche', name='jour_semaine_enum'), nullable=False),
    sa.ForeignKeyConstraint(['id_service'], ['service.id_service'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_horaire'),
    sa.UniqueConstraint('id_service', 'jour_semaine', name='uq_horaire_service_jour')
    )
    op.create_table('role_permission',
    sa.Column('id_role', sa.Integer(), nullable=False),
    sa.Column('id_permission', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_permission'], ['permission.id_permission'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_role'], ['role.id_role'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_role', 'id_permission')
    )
    op.create_table('utilisateur',
    sa.Column('id_utilisateur', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('mot_de_passe_hash', sa.String(length=255), nullable=True),
    sa.Column('auth_provider', sa.Enum('local', 'google', name='auth_provider_enum'), server_default='local', nullable=False),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('email_verifie', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('nom_complet', sa.String(length=150), nullable=False),
    sa.Column('actif', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id_role', sa.Integer(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(auth_provider = 'local' AND mot_de_passe_hash IS NOT NULL) OR (auth_provider = 'google' AND google_id IS NOT NULL)", name='chk_auth_provider'),
    sa.ForeignKeyConstraint(['id_role'], ['role.id_role'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_utilisateur'),
    sa.UniqueConstraint('login')
    )
    op.create_index(op.f('ix_utilisateur_email'), 'utilisateur', ['email'], unique=True)
    op.create_index(op.f('ix_utilisateur_google_id'), 'utilisateur', ['google_id'], unique=True)
    op.create_index(op.f('ix_utilisateur_id_role'), 'utilisateur', ['id_role'], unique=False)
    op.create_table('affectation',
    sa.Column('id_affectation', sa.Integer(), nullable=False),
    sa.Column('id_agent', sa.Integer(), nullable=False),
    sa.Column('id_service', sa.Integer(), nullable=False),
    sa.Column('date_debut', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.Column('service_principal', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['id_agent'], ['agent.id_agent'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_service'], ['service.id_service'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_affectation'),
    sa.UniqueConstraint('id_agent', 'id_service', 'date_debut', name='uq_affectation_agent_service_debut')
    )
    op.create_index(op.f('ix_affectation_id_agent'), 'affectation', ['id_agent'], unique=False)
    op.create_index(op.f('ix_affectation_id_service'), 'affectation', ['id_service'], unique=False)
    op.create_table('code_verification',
    sa.Column('id_code', sa.Integer(), nullable=False),
    sa.Column('id_utilisateur', sa.Integer(), nullable=False),
    sa.Column('type_code', sa.Enum('reset_password', 'verification_email', name='type_code_enum'), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_expiration', sa.DateTime(), nullable=False),
    sa.Column('utilise', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('tentatives', sa.SmallInteger(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['id_utilisateur'], ['utilisateur.id_utilisateur'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_code')
    )
    op.create_index(op.f('ix_code_verification_date_expiration'), 'code_verification', ['date_expiration'], unique=False)
    op.create_index(op.f('ix_code_verification_id_utilisateur'), 'code_verification', ['id_utilisateur'], unique=False)
    op.create_table('empreinte_biometrique',
    sa.Column('id_empreinte', sa.Integer(), nullable=False),
    sa.Column('id_agent', sa.Integer(), nullable=False),
    sa.Column('encodage_facial', sa.LargeBinary(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_agent'], ['agent.id_agent'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_empreinte'),
    sa.UniqueConstraint('id_agent')
    )
    op.create_table('journal_audit',
    sa.Column('id_journal', sa.Integer(), nullable=False),
    sa.Column('id_utilisateur', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=150), nullable=False),
    sa.Column('date_heure', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_utilisateur'], ['utilisateur.id_utilisateur'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_journal')
    )
    op.create_index(op.f('ix_journal_audit_date_heure'), 'journal_audit', ['date_heure'], unique=False)
    op.create_index(op.f('ix_journal_audit_id_utilisateur'), 'journal_audit', ['id_utilisateur'], unique=False)
    op.create_table('pointage',
    sa.Column('id_pointage', sa.Integer(), nullable=False),
    sa.Column('id_agent', sa.Integer(), nullable=False),
    sa.Column('date_heure', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('type_pointage', sa.Enum('entree', 'sortie', name='type_pointage_enum'), nullable=False),
    sa.Column('mode_pointage', sa.Enum('qr', 'badge', 'facial', name='mode_pointage_enum'), nullable=False),
    sa.Column('statut', sa.Enum('valide', 'rejete', 'doublon', name='statut_pointage_enum'), server_default='valide', nullable=False),
    sa.ForeignKeyConstraint(['id_agent'], ['agent.id_agent'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_pointage')
    )
    op.create_index(op.f('ix_pointage_date_heure'), 'pointage', ['date_heure'], unique=False)
    op.create_index(op.f('ix_pointage_id_agent'), 'pointage', ['id_agent'], unique=False)
    op.create_table('rapport',
    sa.Column('id_rapport', sa.Integer(), nullable=False),
    sa.Column('id_utilisateur', sa.Integer(), nullable=True),
    sa.Column('id_service', sa.Integer(), nullable=True),
    sa.Column('type_periode', sa.Enum('jour', 'semaine', 'mois', 'annee', name='type_periode_enum'), nullable=False),
    sa.Column('date_generation', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('format', sa.Enum('pdf', 'excel', name='format_rapport_enum'), nullable=False),
    sa.Column('chemin_fichier', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id_service'], ['service.id_service'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_utilisateur'], ['utilisateur.id_utilisateur'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_rapport')
    )
    op.create_index(op.f('ix_rapport_date_generation'), 'rapport', ['date_generation'], unique=False)
    op.create_index(op.f('ix_rapport_id_service'), 'rapport', ['id_service'], unique=False)
    op.create_index(op.f('ix_rapport_id_utilisateur'), 'rapport', ['id_utilisateur'], unique=False)
    op.create_table('anomalie',
    sa.Column('id_anomalie', sa.Integer(), nullable=False),
    sa.Column('id_agent', sa.Integer(), nullable=False),
    sa.Column('id_pointage', sa.Integer(), nullable=True),
    sa.Column('type_anomalie', sa.Enum('retard', 'absence', 'depart_anticipe', name='type_anomalie_enum'), nullable=False),
    sa.Column('statut_justification', sa.Enum('en_attente', 'justifiee', 'non_justifiee', name='statut_justification_enum'), server_default='en_attente', nullable=False),
    sa.Column('date_detection', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id_utilisateur_traitant', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_agent'], ['agent.id_agent'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_pointage'], ['pointage.id_pointage'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_utilisateur_traitant'], ['utilisateur.id_utilisateur'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_anomalie')
    )
    op.create_index(op.f('ix_anomalie_date_detection'), 'anomalie', ['date_detection'], unique=False)
    op.create_index(op.f('ix_anomalie_id_agent'), 'anomalie', ['id_agent'], unique=False)
    op.create_index(op.f('ix_anomalie_statut_justification'), 'anomalie', ['statut_justification'], unique=False)
    op.create_table('alerte',
    sa.Column('id_alerte', sa.Integer(), nullable=False),
    sa.Column('id_anomalie', sa.Integer(), nullable=False),
    sa.Column('canal', sa.Enum('email', 'sms', name='canal_alerte_enum'), nullable=False),
    sa.Column('date_envoi', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('statut', sa.Enum('envoyee', 'echec', name='statut_alerte_enum'), server_default='envoyee', nullable=False),
    sa.Column('destinataire', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['id_anomalie'], ['anomalie.id_anomalie'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_alerte')
    )
    op.create_index(op.f('ix_alerte_id_anomalie'), 'alerte', ['id_anomalie'], unique=False)
    op.create_table('justificatif',
    sa.Column('id_justificatif', sa.Integer(), nullable=False),
    sa.Column('id_anomalie', sa.Integer(), nullable=False),
    sa.Column('motif', sa.Text(), nullable=False),
    sa.Column('piece_jointe_chemin', sa.Text(), nullable=True),
    sa.Column('date_depot', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_anomalie'], ['anomalie.id_anomalie'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_justificatif'),
    sa.UniqueConstraint('id_anomalie')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('justificatif')
    op.drop_index(op.f('ix_alerte_id_anomalie'), table_name='alerte')
    op.drop_table('alerte')
    op.drop_index(op.f('ix_anomalie_statut_justification'), table_name='anomalie')
    op.drop_index(op.f('ix_anomalie_id_agent'), table_name='anomalie')
    op.drop_index(op.f('ix_anomalie_date_detection'), table_name='anomalie')
    op.drop_table('anomalie')
    op.drop_index(op.f('ix_rapport_id_utilisateur'), table_name='rapport')
    op.drop_index(op.f('ix_rapport_id_service'), table_name='rapport')
    op.drop_index(op.f('ix_rapport_date_generation'), table_name='rapport')
    op.drop_table('rapport')
    op.drop_index(op.f('ix_pointage_id_agent'), table_name='pointage')
    op.drop_index(op.f('ix_pointage_date_heure'), table_name='pointage')
    op.drop_table('pointage')
    op.drop_index(op.f('ix_journal_audit_id_utilisateur'), table_name='journal_audit')
    op.drop_index(op.f('ix_journal_audit_date_heure'), table_name='journal_audit')
    op.drop_table('journal_audit')
    op.drop_table('empreinte_biometrique')
    op.drop_index(op.f('ix_code_verification_id_utilisateur'), table_name='code_verification')
    op.drop_index(op.f('ix_code_verification_date_expiration'), table_name='code_verification')
    op.drop_table('code_verification')
    op.drop_index(op.f('ix_affectation_id_service'), table_name='affectation')
    op.drop_index(op.f('ix_affectation_id_agent'), table_name='affectation')
    op.drop_table('affectation')
    op.drop_index(op.f('ix_utilisateur_id_role'), table_name='utilisateur')
    op.drop_index(op.f('ix_utilisateur_google_id'), table_name='utilisateur')
    op.drop_index(op.f('ix_utilisateur_email'), table_name='utilisateur')
    op.drop_table('utilisateur')
    op.drop_table('role_permission')
    op.drop_table('horaire_reference')
    op.drop_index(op.f('ix_agent_prenom'), table_name='agent')
    op.drop_index(op.f('ix_agent_nom'), table_name='agent')
    op.drop_index(op.f('ix_agent_matricule'), table_name='agent')
    op.drop_index(op.f('ix_agent_id_service'), table_name='agent')
    op.drop_table('agent')
    op.drop_table('service')
    op.drop_table('role')
    op.drop_table('permission')
    op.drop_table('parametre_systeme')
    # ### end Alembic commands ###

    # --- Suppression explicite des types ENUM PostgreSQL ---
    # Alembic autogenerate ne le fait pas automatiquement : les CREATE TYPE
    # sont émis implicitement à la création des tables (upgrade), mais les
    # DROP TYPE ne le sont pas au downgrade. On les supprime ici manuellement,
    # dans n'importe quel ordre (aucune dépendance entre types).
    for enum_name in (
        "statut_agent",
        "jour_semaine_enum",
        "auth_provider_enum",
        "type_code_enum",
        "type_pointage_enum",
        "mode_pointage_enum",
        "statut_pointage_enum",
        "type_periode_enum",
        "format_rapport_enum",
        "type_anomalie_enum",
        "statut_justification_enum",
        "canal_alerte_enum",
        "statut_alerte_enum",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
        