"""check_models

Revision ID: 52f2030bd67b
Revises: 2db6db8a20b9
Create Date: 2026-07-19 20:19:49.884441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52f2030bd67b'
down_revision: Union[str, None] = '2db6db8a20b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    motif_sortie_enum = sa.Enum(
        'normale', 'urgence', 'raison_familiale', 'raison_medicale',
        'autorisation_hierarchie', 'autre',
        name='motif_sortie_enum',
    )
    # Le type ENUM doit être créé explicitement avant l'ALTER COLUMN :
    # alembic/SQLAlchemy ne le fait pas automatiquement dans ce cas.
    motif_sortie_enum.create(op.get_bind(), checkfirst=True)

    # Make idempotent: only add/alter/drop if the target columns exist/are missing.
    bind = op.get_bind()
    insp = sa.inspect(bind)
    existing_cols = [c["name"] for c in insp.get_columns("pointage")] if "pointage" in insp.get_table_names() else []

    if "commentaire" not in existing_cols:
        try:
            op.add_column('pointage', sa.Column('commentaire', sa.Text(), nullable=True))
        except sa.exc.ProgrammingError:
            pass

    if "motif_sortie" in existing_cols:
        op.alter_column('pointage', 'motif_sortie',
                   existing_type=sa.VARCHAR(length=32),
                   type_=motif_sortie_enum,
                   existing_nullable=True,
                   postgresql_using="motif_sortie::motif_sortie_enum")

    if "commentaire_motif" in existing_cols:
        try:
            op.drop_column('pointage', 'commentaire_motif')
        except sa.exc.ProgrammingError:
            pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pointage', sa.Column('commentaire_motif', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.alter_column('pointage', 'motif_sortie',
               existing_type=sa.Enum('normale', 'urgence', 'raison_familiale', 'raison_medicale', 'autorisation_hierarchie', 'autre', name='motif_sortie_enum'),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
    op.drop_column('pointage', 'commentaire')
    # ### end Alembic commands ###