"""Ajout colonne motif_sortie dans pointage

Revision ID: 7f23065a53f7
Revises: 0cfc0c431e8c
Create Date: 2026-07-17 21:30:41.907648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f23065a53f7'
down_revision: Union[str, None] = '0cfc0c431e8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('identifiant_webauthn_credential_id_key', 'identifiant_webauthn', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('identifiant_webauthn_credential_id_key', 'identifiant_webauthn', ['credential_id'])
    # ### end Alembic commands ###